name: Test yml
on: [push]
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
